title: 'Create a parameter'

view: 'WHParameterBundle:Backend/Parameter:modal.html.twig'

formFields:
    - name
    - slug
    - type
    - valueString
    - valueText
    - valueLink
    - image

footerFormFields:
    create:
        label: 'Create'
        field: 'create'
        color: 'success'