actions:
    index:
        route: 'bk_wh_parameter_parameter_index'
    create:
        route: 'bk_wh_parameter_parameter_create'
    update:
        route: 'bk_wh_parameter_parameter_update'
        parameters:
            id: 'id'
    delete:
        route: 'bk_wh_parameter_parameter_delete'
        parameters:
            id: 'id'

formFields:
    name:
        label: 'Name'
        field: 'name'
        type: 'text'
    slug:
        label: 'Technical name'
        field: 'slug'
        type: 'text'
    type:
        label: 'Type'
        field: 'type'
        type: 'choice'
        options:
            type: 'static'
            field: 'types'
    value:
        label: 'Value'
        field: 'value'
        type: 'text'
    valueString:
        label: 'Short value'
        field: 'valueString'
        type: 'text'
    valueText:
        label: 'Long value'
        field: 'valueText'
        type: 'textarea'
    valueLink:
        label: 'URL'
        field: 'valueLink'
        type: 'text'

menus:
    main: 'backendMenu'
    right: 'backendMenuRight'