title: 'Parameters list'

view: 'WHParameterBundle:Backend/Parameter:index.html.twig'

breadcrumb:
    index:
        label: 'Parameters list'
        action: 'index'

tablePanelProperties:
    headerLabel: 'Parameters list'
    headerListButtons:
        create:
            buttonType: 'link'
            color: 'success'
            label: 'Create a parameter'
            action: 'create'
            modal: 'true'
            size: 'xs'
    tableFields:
        buttons:
            multipleFields:
            update:
                icon: 'pencil'
                action: 'update'
                modal: 'true'
            delete:
                icon: 'trash'
                color: 'danger'
                action: 'delete'
                confirm: 'Do you really want to delete this parameter ?'
        id:
        name:
        value:
