modal: 'true'

view: 'WHParameterBundle:Backend/Parameter:modal.html.twig'

title: 'Edit a parameter'

formFields:
    - name
    - slug
    - type
    - valueString
    - valueText
    - valueLink

footerFormFields:
    save:
        label: 'Save'
        field: 'save'
        color: 'success'
